<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190320151045 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE languages_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, name VARCHAR(255) DEFAULT \'\', code VARCHAR(2) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_9480a6f9f730048a6684eaa36a2b229c_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE carriers_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, default_language_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', billing_carrier_id INT DEFAULT NULL, operator_id INT DEFAULT 0, name VARCHAR(255) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, isp VARCHAR(255) DEFAULT NULL, published TINYINT(1) DEFAULT \'0\', lp_otp TINYINT(1) DEFAULT \'0\', pin_ident_support TINYINT(1) DEFAULT \'0\', trial_initializer VARCHAR(10) DEFAULT \'carrier\', trial_period INT DEFAULT 0, subscription_period INT DEFAULT 7, resub_allowed TINYINT(1) DEFAULT \'0\', is_campaigns_on_pause TINYINT(1) DEFAULT \'0\', number_of_allowed_subscription INT DEFAULT 1, is_unlimited_subscription_attempts_allowed TINYINT(1) DEFAULT \'1\', is_captcha TINYINT(1) DEFAULT \'0\', number_of_allowed_subscriptions_by_constraint INT DEFAULT NULL, redirect_url VARCHAR(255) DEFAULT NULL, counter INT DEFAULT 0, flush_date DATE DEFAULT NULL, is_cap_alert_dispatch TINYINT(1) DEFAULT \'0\', revtype VARCHAR(4) NOT NULL, INDEX rev_51a3bede3259d34c6b18fd9ccf7a6be3_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admins_audit (id INT NOT NULL, rev INT NOT NULL, username VARCHAR(180) DEFAULT NULL, username_canonical VARCHAR(180) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, email_canonical VARCHAR(180) DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', revtype VARCHAR(4) NOT NULL, INDEX rev_33fee45a8144ae15780cadf1c6bc5d7f_idx (rev), PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE affiliates_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) DEFAULT NULL, type INT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, postback_url VARCHAR(255) DEFAULT NULL, commercial_contact VARCHAR(255) DEFAULT NULL, technical_contact VARCHAR(255) DEFAULT NULL, skype_id VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, sub_price_name VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_b352fc651640200898d48bbc6761f265_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE campaigns_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, affiliate_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', main_category_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', image_name VARCHAR(255) DEFAULT NULL, bg_color VARCHAR(7) DEFAULT \'#000000\', text_color VARCHAR(7) DEFAULT \'#000000\', campaign_token VARCHAR(255) DEFAULT NULL, test_url VARCHAR(255) DEFAULT NULL, is_pause TINYINT(1) DEFAULT \'0\', counter INT DEFAULT 0, flush_date DATE DEFAULT NULL, ppd NUMERIC(10, 2) DEFAULT NULL, sub NUMERIC(10, 2) DEFAULT NULL, click NUMERIC(10, 2) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_bb7af6fe185f2a62d145aed138f55da4_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country_category_priority_overrides_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, main_category_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', menu_priority INT DEFAULT 0, revtype VARCHAR(4) NOT NULL, INDEX rev_783ca19f2b39f5a38f0ec39e8fdc5a08_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE developers_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_f980aae9184d1e595083a017531b0e4f_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE games_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, developer_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', tier_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, thumbnail VARCHAR(255) DEFAULT NULL, rating INT DEFAULT NULL, published TINYINT(1) DEFAULT \'0\', is_bookmark TINYINT(1) DEFAULT \'0\', created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, deleted_at DATE DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_b7d5348675f7ee6061c89022a9ebb16f_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE game_builds_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, game_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', os_type INT DEFAULT NULL, min_os_version VARCHAR(255) DEFAULT NULL, game_apk VARCHAR(255) DEFAULT NULL, apk_size INT DEFAULT NULL, version INT DEFAULT NULL, apk_version VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_b2643daa77b83ae1a514a7360ea031a2_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE game_images_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, game_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', name VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_8b95574e911270d3a395f650125ed5d9_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE main_categories_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, title VARCHAR(255) DEFAULT NULL, menu_priority INT DEFAULT 0, revtype VARCHAR(4) NOT NULL, INDEX rev_c8103757188cf186dfb568ec79e0301d_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subcategories_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, parent CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', title VARCHAR(255) DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_ef4955e680f33be77a872ff7751cb3c1_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE translations_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, language_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', carrier_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', `key` VARCHAR(255) DEFAULT NULL, translation LONGTEXT DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_496ba891b6be16f83dc1b2124ae8f693_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE uploaded_video_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, subcategory_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', status SMALLINT DEFAULT NULL, remote_url VARCHAR(255) DEFAULT NULL, remote_id VARCHAR(255) DEFAULT NULL, created_date DATETIME DEFAULT CURRENT_TIMESTAMP, expired_date DATETIME DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, thumbnails LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', revtype VARCHAR(4) NOT NULL, INDEX rev_787c894a53583a8a3fb841024403365e_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, carrier_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', identifier VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, ip VARCHAR(15) DEFAULT NULL, affiliate_token LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json_array)\', url_id VARCHAR(100) DEFAULT NULL, short_url_id VARCHAR(100) DEFAULT NULL, added DATETIME DEFAULT CURRENT_TIMESTAMP, identification_process_id VARCHAR(255) DEFAULT NULL, identification_token VARCHAR(255) DEFAULT NULL, connection_type VARCHAR(255) DEFAULT NULL, device_model VARCHAR(255) DEFAULT NULL, device_manufacturer VARCHAR(255) DEFAULT NULL, identification_url LONGTEXT DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_e06395edc291d0719bee26fd39a32e8a_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subscription_packs_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, country_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', status TINYINT(1) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_resub_allowed TINYINT(1) DEFAULT \'0\', carrier_name VARCHAR(255) DEFAULT NULL, carrier_id INT DEFAULT NULL, tier_name VARCHAR(255) DEFAULT NULL, tier_id INT DEFAULT NULL, tier_price NUMERIC(14, 2) DEFAULT NULL, tier_currency VARCHAR(3) DEFAULT \'\', display_currency VARCHAR(10) DEFAULT \'\', credits BIGINT DEFAULT NULL, periodicity SMALLINT DEFAULT NULL, custom_renew_period SMALLINT DEFAULT NULL, grace_period SMALLINT UNSIGNED DEFAULT 0, unlimited_grace_period TINYINT(1) DEFAULT \'0\', preferred_renewal_start TIME DEFAULT NULL, preferred_renewal_end TIME DEFAULT NULL, welcome_sms_text LONGTEXT DEFAULT NULL, renewal_sms_text LONGTEXT DEFAULT NULL, unsubscribe_sms_text LONGTEXT DEFAULT NULL, buy_strategy_name VARCHAR(255) DEFAULT NULL, buy_strategy_id INT DEFAULT NULL, renew_strategy_name VARCHAR(255) DEFAULT NULL, renew_strategy_id INT DEFAULT NULL, unlimited TINYINT(1) DEFAULT NULL, is_first_subscription_free_multiple TINYINT(1) DEFAULT \'0\', is_first_subscription_free TINYINT(1) DEFAULT \'0\', allow_bonus_credit TINYINT(1) DEFAULT \'0\', allow_bonus_credit_multiple TINYINT(1) DEFAULT \'0\', bonus_credit SMALLINT DEFAULT 0, provider_managed_subscriptions TINYINT(1) DEFAULT \'0\', created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_56bb5620d848a8cf066743ad81349190_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subscriptions_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', subscription_pack_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', credits BIGINT DEFAULT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, status SMALLINT DEFAULT NULL, renew_date DATETIME DEFAULT NULL, last_renew_alert_date DATETIME DEFAULT NULL, current_stage SMALLINT DEFAULT NULL, redirect_url LONGTEXT DEFAULT NULL, affiliate_token LONGTEXT DEFAULT NULL, error VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_aa3db939606b921bfbfeaa4db3cd2698_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE black_list_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, billing_carrier_id INT DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL, is_blocked_manually TINYINT(1) DEFAULT \'1\', added_at DATETIME DEFAULT CURRENT_TIMESTAMP, revtype VARCHAR(4) NOT NULL, INDEX rev_4241d4a1708646706f8cab222de00ce1_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refunds_audit (uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', rev INT NOT NULL, user_id CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', bf_charge_process_id INT DEFAULT NULL, bf_refund_process_id INT DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, error VARCHAR(255) DEFAULT NULL, attempt_date DATETIME DEFAULT CURRENT_TIMESTAMP, refund_value INT DEFAULT NULL, revtype VARCHAR(4) NOT NULL, INDEX rev_9a55fd9f8c83806c48e8dc506ccf19df_idx (rev), PRIMARY KEY(uuid, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE revisions (id INT AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL, username VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE languages_audit');
        $this->addSql('DROP TABLE carriers_audit');
        $this->addSql('DROP TABLE admins_audit');
        $this->addSql('DROP TABLE affiliates_audit');
        $this->addSql('DROP TABLE campaigns_audit');
        $this->addSql('DROP TABLE country_category_priority_overrides_audit');
        $this->addSql('DROP TABLE developers_audit');
        $this->addSql('DROP TABLE games_audit');
        $this->addSql('DROP TABLE game_builds_audit');
        $this->addSql('DROP TABLE game_images_audit');
        $this->addSql('DROP TABLE main_categories_audit');
        $this->addSql('DROP TABLE subcategories_audit');
        $this->addSql('DROP TABLE translations_audit');
        $this->addSql('DROP TABLE uploaded_video_audit');
        $this->addSql('DROP TABLE user_audit');
        $this->addSql('DROP TABLE subscription_packs_audit');
        $this->addSql('DROP TABLE subscriptions_audit');
        $this->addSql('DROP TABLE black_list_audit');
        $this->addSql('DROP TABLE refunds_audit');
        $this->addSql('DROP TABLE revisions');
    }
}
