<?php
/**
 * Created by PhpStorm.
 * User: dmitriy
 * Date: 11.01.19
 * Time: 10:46
 */

use IdentificationBundle\Entity\CarrierInterface;
use IdentificationBundle\Identification\Common\HeaderEnrichmentHandler;
use IdentificationBundle\Identification\Handler\HasHeaderEnrichment;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\Storage\MockArraySessionStorage;

class HeaderEnrichmentHandlerErrorsTest extends \PHPUnit\Framework\TestCase
{


    /**
     * @var \Mockery\MockInterface|\IdentificationBundle\Identification\Common\HeaderEnrichmentHandler
     */
    private $headerEnrichmentHandler;
    /**
     * @var \Mockery\MockInterface|\Doctrine\ORM\EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var \Mockery\MockInterface|\IdentificationBundle\Identification\Service\UserFactory
     */
    private $userFactory;
    /**
     * @var \Mockery\MockInterface|\IdentificationBundle\Repository\UserRepository
     */
    private $userRepository;
    private $session;
    private $dataStorage;
    private $identificationStatus;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {

        $this->entityManager  = Mockery::spy(\Doctrine\ORM\EntityManagerInterface::class);
        $this->userRepository = Mockery::spy(\IdentificationBundle\Repository\UserRepository::class);
        $this->userFactory    = new \IdentificationBundle\Identification\Service\UserFactory();
        $this->session        = new Session(new MockArraySessionStorage());
        $this->dataStorage    = new \IdentificationBundle\Identification\Service\IdentificationDataStorage($this->session);

        $this->identificationStatus = new \IdentificationBundle\Identification\Service\IdentificationStatus($this->dataStorage);

        $this->headerEnrichmentHandler = new HeaderEnrichmentHandler(
            $this->userFactory,
            $this->entityManager,
            $this->userRepository,
            $this->identificationStatus
        );

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testNoErrorWhenMsisdnPresent()
    {

        $request = new Request([], [], [], [], [], ['REMOTE_ADDR' => '127.0.0.1']);

        $handler = Mockery::spy(HasHeaderEnrichment::class);
        $handler->allows(['getMsisdn' => 'msisdn']);

        $carrier = Mockery::spy(CarrierInterface::class);

        $this->headerEnrichmentHandler->process($request, $handler, $carrier, 'token');

        $this->assertTrue(true);
    }

    public function testErrorWhenNoMsisdn()
    {
        $this->expectException(\IdentificationBundle\Identification\Exception\FailedIdentificationException::class);

        $request = new Request([], [], [], [], [], ['REMOTE_ADDR' => '127.0.0.1']);

        $handler = Mockery::spy(HasHeaderEnrichment::class);
        $carrier = Mockery::spy(CarrierInterface::class);

        $this->headerEnrichmentHandler->process($request, $handler, $carrier, 'token');

    }
}
