<?php
/**
 * Created by PhpStorm.
 * User: Администратор
 * Date: 13.01.2019
 * Time: 21:08
 */

namespace ExtrasBundle;


use ExtrasBundle\Testing\CompilerPass\PublicForTestsCompilerPass;
use Symfony\Component\DependencyInjection\Compiler\PassConfig;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class ExtrasBundle extends Bundle
{
    public function build(ContainerBuilder $container)    {

        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new PublicForTestsCompilerPass(),PassConfig::TYPE_AFTER_REMOVING);

    }


}