<?php

namespace App\Domain\Repository;

/**
 * UploadedVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadedVideoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithCategories(): array
    {
        $q = $this->createQueryBuilder('v')
            ->leftJoin('v.subcategory', 'subcategory')
            ->leftJoin('subcategory.parent', 'category')
            ->addSelect('subcategory', 'category');


        return $q->getQuery()->getResult();
    }
}
