<?php

namespace App\Domain\Repository;

/**
 * UploadedVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadedVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
