<?php

namespace App\Domain\Repository;

/**
 * VideoCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
