<?php
/**
 * Created by PhpStorm.
 * User: dmitriy
 * Date: 24.05.18
 * Time: 13:26
 */

namespace ExtrasBundle\Development\DBAL\Sqlite;


use Doctrine\DBAL\Platforms\SqlitePlatform;
use Doctrine\DBAL\Schema\Index;

class Platform extends SqlitePlatform
{
    public function getCreateIndexSQL(Index $index, $table)
    {
        $index = new TablePostfixedIndex(
            $index->getName(),
            $index->getColumns(),
            $index->isUnique(),
            $index->isPrimary(),
            $index->getFlags(),
            $index->getOptions(),
            $table
        );

        return parent::getCreateIndexSQL($index, $table); // TODO: Change the autogenerated stub
    }

}