<?php

namespace SubscriptionBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SubscriptionBundle\Entity\SubscriptionPack;

/**
 * SubscriptionPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionPackRepository extends EntityRepository
{

    /**
     * @param SubscriptionPack $subscriptionPack
     *
     * @return array
     */
    public function getActiveSubscriptionPacksByCarrierUuid(SubscriptionPack $subscriptionPack)
    {
        $qb = $this->createQueryBuilder('sp');

        $query = $qb
            ->where('sp.status = :status ')
            ->andWhere('sp.carrier = :carrier')
            ->andWhere('sp.uuid != :uuid')
            ->setParameters([
                'status' => SubscriptionPack::ACTIVE_SUBSCRIPTION_PACK,
                'carrier' => $subscriptionPack->getCarrier(),
                'uuid' => $subscriptionPack->getUuid()
            ])
            ->getQuery();

        return $query->getResult();
    }
}
