<?php

namespace SubscriptionBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;
use SubscriptionBundle\Entity\SubscriptionPack;

/**
 * SubscriptionPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionPackRepository extends EntityRepository
{

    /**
     * @param $subscriptionPack
     * @return null | string
     */
    public function getOtherActiveSubscriptionPack(SubscriptionPack $subscriptionPack)
    {
        $qb = $this->createQueryBuilder('sp');
        $qb->select('sp.uuid')
            ->where('sp.status = :status ')
            ->andWhere('sp.carrierId = :carrierId')
            ->setParameter('status', SubscriptionPack::ACTIVE_SUBSCRIPTION_PACK)
            ->setParameter('carrierId', $subscriptionPack->getCarrierId());

        if ($subscriptionPack->getUuid()) {
            $qb->andWhere('sp.id != :id')->setParameter('id', $subscriptionPack->getUuid());
        }

        $existingActivePackForSelectedCarrier = $qb->getQuery()
            ->getOneOrNullResult(AbstractQuery::HYDRATE_SINGLE_SCALAR);
        return $existingActivePackForSelectedCarrier;
    }

    /**
     * @param SubscriptionPack $subscriptionPack
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCarrier(SubscriptionPack $subscriptionPack)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Carrier', 'c')
            ->where('c.id_carrier = :idCarrier')
            ->setParameter('idCarrier', $subscriptionPack->getCarrierId())
        ;
        $oCarrier = $qb->getQuery()->getOneOrNullResult(AbstractQuery::HYDRATE_SINGLE_SCALAR);
        return $oCarrier;
    }
}
