<?php
/**
 * Created by PhpStorm.
 * User: dmitriy
 * Date: 07.06.18
 * Time: 17:16
 */

namespace Service\Action\Subscribe;


use App\Utils\UuidGenerator;
use Mockery;
use SubscriptionBundle\Entity\Subscription;
use SubscriptionBundle\Service\EntitySaveHelper;

class RedirectUrlNullifierTest extends \PHPUnit\Framework\TestCase
{
    use Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration;

    /**
     * @var EntitySaveHelper|Mockery\MockInterface
     *
     */
    private $entitySaveHelper;
    /**
     * @var \SubscriptionBundle\Service\Action\Common\RedirectUrlNullifier|Mockery\MockInterface
     */
    private $redirectNullifier;

    public function testIsUrlCorrectlyNullified()
    {
        $subscription = new Subscription(UuidGenerator::generate());
        $subscription->setRedirectUrl('url');

        $this->redirectNullifier->processSubscriptionAndSave($subscription);

        $this->assertNull($subscription->getRedirectUrl(), 'url is not correctly nullified');
        $this->entitySaveHelper->shouldHaveReceived('persistAndSave')->once();

    }

    protected function setUp()
    {
        $this->entitySaveHelper  = Mockery::spy(EntitySaveHelper::class);
        $this->redirectNullifier = new \SubscriptionBundle\Service\Action\Common\RedirectUrlNullifier(
            $this->entitySaveHelper
        );

        parent::setUp(); // TODO: Change the autogenerated stub
    }


}