<?php

namespace IdentificationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use IdentificationBundle\Entity\PinCode;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinCodeRepository extends EntityRepository
{
    /**
     * Select pin code, that have been added less then 15 minutes ago
     *
     * @param $pinCode
     * @return PinCode|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getActivePinCode($pinCode)
    {
        $qb = $this->createQueryBuilder('pc');
        $qb
            ->andWhere('pc.pin = :pinCode')
            ->andWhere($qb->expr()->gte('pc.addedAt', ':expDate'))
            ->setParameter('pinCode', $pinCode)
            ->setParameter('expDate', new \DateTime('-15 min'));

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * Deleting all the expired (stored more than 15 minutes) pinCodes
     */
    public function deleteExpiredPinCodes()
    {
        $qb = $this->createQueryBuilder('pc');
        $qb->delete($this->getEntityName(), 'pc')
            ->andWhere($qb->expr()->lte('pc.addedAt', ':expDate'))
            ->setParameter('expDate', new \DateTime('-15 min'))
            ->getQuery()
            ->execute();
    }
}
