<?php

namespace App\Admin\Sonata;

use App\Domain\Service\VideoProcessing\Connectors\CloudinaryConnector;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;
use Sonata\AdminBundle\Show\ShowMapper;
use App\Domain\Entity\UploadedVideo;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class UploadedVideoAdmin extends AbstractAdmin
{
    /**
     * @var CloudinaryConnector
     */
    private $cloudinaryConnector;

    /**
     * UploadedVideoAdmin constructor
     *
     * @param string $code
     * @param string $class
     * @param string $baseControllerName
     * @param CloudinaryConnector $cloudinaryConnector
     */
    public function __construct(
        string $code,
        string $class,
        string $baseControllerName,
        CloudinaryConnector $cloudinaryConnector
    ) {
        $this->cloudinaryConnector = $cloudinaryConnector;

        parent::__construct($code, $class, $baseControllerName);
    }

    public function getBatchActions()
    {
        return [];
    }

    /**
     * @param DatagridMapper $datagridMapper
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('status')
            ->add('remoteId')
            ->add('title');
    }

    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        unset($this->listModes['mosaic']);

        $listMapper
            ->add('uuid')
            ->add('remoteId')
            ->add('title')
            ->add('status', ChoiceType::class, [
                'choices' => UploadedVideo::STATUSES
            ])
            ->add('createdAt')
            ->add('_action', null, array(
                'actions' => array(
                    'show'   => array(),
                    'edit'   => array(),
                    'delete' => array(),
                )
            ));
    }

    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('title')
            ->add('description', TextareaType::class);
    }

    /**
     * @param ShowMapper $showMapper
     */
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')
            ->add('remoteId')
            ->add('title')
            ->add('description')
            ->add('status', 'choice', ['choices' => UploadedVideo::STATUSES])
            ->add('thumbnail', null, [
                'template' => '@Admin/UploadedVideo/thumbnail.html.twig',
                'mapped'   => false,
                'label'    => 'Thumbnails'
            ])
            ->add('player', null, [
                'template' => '@Admin/UploadedVideo/player.html.twig',
                'mapped'   => false,
                'label'    => 'Video Preview'
            ])
            ->add('category', null, ['associated_property' => 'title'])
            ->add('createdAt');
    }

    protected function configureRoutes(RouteCollection $collection)
    {
        $collection->clearExcept(['show', 'list', 'edit', 'delete']);

        $collection->add('upload', 'upload');


        parent::configureRoutes($collection); // TODO: Change the autogenerated stub
    }

    /**
     * @param $action
     * @param null $object
     *
     * @return array
     */
    public function configureActionButtons($action, $object = null)
    {
        $list = parent::configureActionButtons($action, $object);

        $list['import']['template'] = '@Admin/UploadedVideo/upload_button.html.twig';

        return $list;
    }

    /**
     * @param UploadedVideo $uploadedVideo
     */
    public function postRemove($uploadedVideo)
    {
        $this->cloudinaryConnector->deleteVideo($uploadedVideo->getRemoteId());
    }
}